# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
from sklearn.linear_model import Perceptron

In [4]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [7]:
standardized_X_test[0:10,]

array([[-1.47628928,  0.79136012, -1.34348133, -1.49203165],
       [-0.088325  , -0.14886973,  0.21824063,  0.42840513],
       [ 0.41638928, -1.79427196,  0.33837309,  0.13295332],
       [-0.71921785,  0.79136012, -1.40354756, -1.19657984],
       [-0.088325  , -0.14886973,  0.7588367 ,  0.87158284],
       [ 0.29021071, -0.38392719,  0.27830686,  0.13295332],
       [ 0.54256785,  0.08618774,  0.99910162,  0.87158284],
       [ 0.66874642, -0.14886973,  1.17930031,  1.46248647],
       [-1.35011071,  0.08618774, -1.40354756, -1.63975755],
       [-0.34068214,  1.73158997, -1.2834151 , -1.34430574]])

In [8]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [9]:
y_pred = perceptron.predict(standardized_X_test)

In [10]:
print(y_test)

[0 1 1 0 2 1 2 2 0 0 0 2 1 0 0 1 1 1 1 1 0 2 1 2 2 2 0 1 1 1]


In [11]:
print(y_pred)

[0 0 1 0 2 1 2 2 0 0 0 2 0 0 0 1 1 1 0 1 0 2 0 2 2 2 0 0 0 0]


In [12]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.56      1.00      0.72         9
           1       1.00      0.46      0.63        13
           2       1.00      1.00      1.00         8

    accuracy                           0.77        30
   macro avg       0.85      0.82      0.78        30
weighted avg       0.87      0.77      0.76        30



In [13]:
print(confusion_matrix(y_test, y_pred))

[[9 0 0]
 [7 6 0]
 [0 0 8]]
